site_name: Дурка
nav:
    - Что это: index.md
    - Матан:
      - Лекция 1: ./math/a.md

theme: 
  name: material
  language: ru
  palette:
    scheme: default
    primary: green
    accent: indigo
  
  features:
    - instant
    - tabs

extra_css:
  - style.css
  - https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css

extra_javascript:
  - katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/auto-render.min.js
  

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.highlight
    - pymdownx.arithmatex:
        generic: true

plugins:
    - search:
        lang:
          - ru
          - en

copyright: Дурка